'''
To ensure that local images referenced in your HTML file are correctly included in the PDF generated by pdfkit, you need to make sure that the image paths in the HTML are correctly specified relative to the location of the HTML file. When pdfkit processes the HTML file, it will access the images using these paths.

If your HTML and images are in the same directory as your Jupyter notebook (.ipynb file), your HTML image tags should reference the images with relative paths. For example:
'''
# HTML
# <img src="image1.png" alt="Image 1">
'''
In this example, image1.png is located in the same directory as both the HTML file and your Jupyter notebook.

Here's how you would use pdfkit in a Jupyter notebook to convert the HTML to a PDF, ensuring local images are included:
'''
import pdfkit
import os


def convert_html_to_pdf(html_file_name, pdf_file_name):
    """
    Convert an HTML file to a PDF file using pdfkit.

    :param html_file_name: The name of the HTML file (assumed to be in the same directory as the notebook).
    :param pdf_file_name: The name for the output PDF file.
    """
    # Get the current directory (where the notebook and HTML file are located)
    current_dir = os.getcwd()

    # Construct full file paths
    html_file_path = os.path.join(current_dir, html_file_name)
    output_pdf_path = os.path.join(current_dir, pdf_file_name)

    try:
        # Convert HTML to PDF
        pdfkit.from_file(html_file_path, output_pdf_path)
        print(f"PDF file has been created at {output_pdf_path}")
    except Exception as e:
        print(f"An error occurred: {e}")


# Example usage
convert_html_to_pdf('complex_layout_page.html', 'output.pdf')


'''
This function gets the current working directory (where your Jupyter notebook is running), then constructs the full paths to the HTML file and the desired output PDF file based on that directory. It then uses pdfkit to perform the conversion, ensuring that local images are correctly referenced and included.

Make sure that wkhtmltopdf is installed on your system as pdfkit is a wrapper around this tool. The installation process for wkhtmltopdf can vary depending on your operating system, and you may need to specify the path to the wkhtmltopdf executable in the pdfkit.from_file call if it's not automatically detected.
'''